apiVersion: apps/v1 
kind: Deployment
metadata:
  name: nile
  labels: 
   app: clauders
spec:
  replicas: 2
  selector:
    matchLabels:
      app: claudera
  template:
    metadata:
     labels:
       app: claudera
    spec:
      containers:
      - name: cont1
        image: cronosm4m/claudera:c05eb6169bcfd10fb93d0f9e1e2ff1a2aa27582c



---
apiVersion: v1 
kind: Service
metadata:
  name: serving-v1
spec:
  type: NodePort
  selector:
    app: claudera
  ports:
  - port: 80  #this is for the service
    targetPort: 80 #this is for the container port.
